# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Neurosymbolic Programming Tutorial (POPL 2023)
author: Neurosymbolic Team (neurosymbolic.org)

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: 'off'

# Information about where the book exists on the web
repository:
  url: https://github.com/neurosymbolic-learning/Neurosymbolic_Tutorial  # Online location of your book
  branch: popl23  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true

# parse:
#   myst_enable_extensions:
#     # don't forget to list any other extensions you want enabled,
#     # including those that are enabled by default!
#     - html_image

launch_buttons:
  colab_url: "https://colab.research.google.com"
  binderhub_url: ""